### PR TITLE
add a simple websocket tunnel

### PR DESCRIPTION
**Pull request by tehn**
(creating a PR for easy testing by others)

send commands to druid (ie, forward to crow) via websocket port 6666

rationale is to facilitate editor extensions (vim/etc) for line/region execution

### CODE REVIEW

**Comment by tehn** [comment]
note:

```
pip install websockets
```

**Comment by tehn** [comment]
test_ws.py was hanging for me after the first command, but everything works great using `websocat` as the client: https://github.com/vi/websocat

next thing i'll look into is multi-line parsing (i don't remember how we did this for crow)

conceivably, writing an editor plugin could mean just passing the selection to websocat (for vim this could just be a macro, not even a plugin)

**Comment by trentgill** [comment]
@tehn i believe the idiomatic approach for multiline is to send ` ``` ` (3 backticks) before & after the chunk. crow will buffer the chunk until the closing backticks are received, at which point it will execute the whole chunk at once.

**Comment by tehn** [comment]
@trentgill whoa, i forgot about this, and also confirmed that you can do multi-line via druid just by using the backticks! this hugely simplifies the editor extensions as well

**Comment by tehn** [comment]
looking for the correct way to handle a dropped client connection. i can't quite figure out how to ask the server _not_ to send confirmation/responses... so in the meantime here's a terrible hack:

```
        try:
            async for message in websocket:
                self.repl.output(f'\n> {message}\n')
                self.repl.crow.writeline(message)
        except:
            pass
```

the idea being, i don't think this needs to be bidirectional--- druid will always be open for display, so we're just aiming for text-copy from the editor.

**Comment by tehn** [comment]
here's a single-line vim keymapping:

```
nmap <F1> :silent .w !websocat ws://localhost:6666 -1
```

**Comment by tehn** [comment]
@csboling this is working great! i'd love to merge this code you made--- but i'm not comfortable doing it with my ugly `except: pass` hack as shown above... unless that's, uh, ok. would love your blessing or suggestion otherwise.

**Comment by csboling** [comment]
https://github.com/monome/druid/pull/71/commits/c45dcade5fe62875967b5a8f6a572c72d68043db should catch this error and show clearer messaging about the state of the websocket connection. Example output from a (ipv6 loopback) client that connects, disconnects cleanly, connects again, then aborts the connection by killing the client process.

```
//// druid. q to quit. h for help

 <crow connected>
 <listening at ws://localhost:6666>
 <ws connected: ::1>
 <ws disconnected: ::1>
 <ws connected: ::1>
 <ws disconnected: ::1 (1006 no reason)>
```

Also I don't know if there is any particular TCP port assignment scheme, 6666 made some degree of sense to me because 1) matron is 5555 2) it is the same key as `^^`

**Comment by tehn** [comment]
thank you! i now have a way better understanding of exceptions in python

**Pull request merged**
